name: Push Images

on:
  push:
    branches: dockerhub
    paths:
      [
        "backend/**",
        "db-lambda/**",
        "frontend/**",
        "scala-spark-lambda/**",
        "spark-lambda/**",
        ".github/workflows/push-images.yml",
      ]

jobs:
  spark:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spark-lambda
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.5.0
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build arm64 Image
        run: docker build --platform linux/arm64 -t davidzajac1/zillacode-spark:arm64 .
      - name: Push arm64 Image
        run: docker push davidzajac1/zillacode-spark:arm64
      - name: Build amd64 Image
        run: docker build --platform linux/amd64 -t davidzajac1/zillacode-spark:amd64 .
      - name: Push amd64 Image
        run: docker push davidzajac1/zillacode-spark:amd64
      - name: Create Manifest
        run: docker manifest create davidzajac1/zillacode-spark:latest --amend davidzajac1/zillacode-spark:amd64 --amend davidzajac1/zillacode-spark:arm64
      - name: Push Manifest
        run: docker manifest push davidzajac1/zillacode-spark:latest
  scala-spark:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scala-spark-lambda
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.5.0
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build arm64 Image
        run: docker build --platform linux/arm64 -t davidzajac1/zillacode-scala-spark:arm64 .
      - name: Push arm64 Image
        run: docker push davidzajac1/zillacode-scala-spark:arm64
      - name: Build amd64 Image
        run: docker build --platform linux/amd64 -t davidzajac1/zillacode-scala-spark:amd64 .
      - name: Push amd64 Image
        run: docker push davidzajac1/zillacode-scala-spark:amd64
      - name: Create Manifest
        run: docker manifest create davidzajac1/zillacode-scala-spark:latest --amend davidzajac1/zillacode-scala-spark:amd64 --amend davidzajac1/zillacode-scala-spark:arm64
      - name: Push Manifest
        run: docker manifest push davidzajac1/zillacode-scala-spark:latest
  db-service:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: db-lambda
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.5.0
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build arm64 Image
        run: docker build --platform linux/arm64 -t davidzajac1/zillacode-db-service:arm64 .
      - name: Push arm64 Image
        run: docker push davidzajac1/zillacode-db-service:arm64
      - name: Build amd64 Image
        run: docker build --platform linux/amd64 -t davidzajac1/zillacode-db-service:amd64 .
      - name: Push amd64 Image
        run: docker push davidzajac1/zillacode-db-service:amd64
      - name: Create Manifest
        run: docker manifest create davidzajac1/zillacode-db-service:latest --amend davidzajac1/zillacode-db-service:amd64 --amend davidzajac1/zillacode-db-service:arm64
      - name: Push Manifest
        run: docker manifest push davidzajac1/zillacode-db-service:latest
  backend:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.5.0
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build arm64 Image
        run: docker build --platform linux/arm64 -t davidzajac1/zillacode-backend:arm64 .
      - name: Push arm64 Image
        run: docker push davidzajac1/zillacode-backend:arm64
      - name: Build amd64 Image
        run: docker build --platform linux/amd64 -t davidzajac1/zillacode-backend:amd64 .
      - name: Push amd64 Image
        run: docker push davidzajac1/zillacode-backend:amd64
      - name: Create Manifest
        run: docker manifest create davidzajac1/zillacode-backend:latest --amend davidzajac1/zillacode-backend:amd64 --amend davidzajac1/zillacode-backend:arm64
      - name: Push Manifest
        run: docker manifest push davidzajac1/zillacode-backend:latest
  frontend:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.5.0
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build arm64 Image
        run: docker build --platform linux/arm64 -t davidzajac1/zillacode-frontend:arm64 .
      - name: Push arm64 Image
        run: docker push davidzajac1/zillacode-frontend:arm64
      - name: Build amd64 Image
        run: docker build --platform linux/amd64 -t davidzajac1/zillacode-frontend:amd64 .
      - name: Push amd64 Image
        run: docker push davidzajac1/zillacode-frontend:amd64
      - name: Create Manifest
        run: docker manifest create davidzajac1/zillacode-frontend:latest --amend davidzajac1/zillacode-frontend:amd64 --amend davidzajac1/zillacode-frontend:arm64
      - name: Push Manifest
        run: docker manifest push davidzajac1/zillacode-frontend:latest
